apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-nginx
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen 80;
      root /usr/share/nginx/html;
      index index.html;

      location /api {
        proxy_pass http://{{ .Values.api.serviceName }}:{{ .Values.api.servicePort }};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }

      location / {
        try_files $uri $uri/ /index.html;
      }
    }
