{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: umbrella-api
  namespace: bootcamp
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - bootcamp
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
{{- end }}